---

- name: "Set all users with view access to various namespaces to include {{ maistra_operator_namespace }}"
  shell: |
    oc adm policy add-role-to-user view user{{ item }} -n {{ maistra_operator_namespace }}
    oc adm policy add-role-to-user view user{{ item }} -n admin{{ item }}-istio-system

    oc adm policy add-role-to-user view admin{{ item }} -n {{ maistra_operator_namespace }}
    oc adm policy add-role-to-user admin admin{{ item }} -n user{{ item }}-{{ er_demo_namespace_suffix }}

    # Needed to review CRDs
    oc adm policy add-cluster-role-to-user sudoer admin{{ item }}

    # Needed for operating with 3scale API Mgmt tenants
    oc adm policy add-role-to-user view admin{{ item }} -n {{ API_MANAGER_NS }}
  loop: "{{ range(start_id|int, end_id|int + 1, 1)|list }}"
