---

- shell: |
    {{ openshift_cli }} get deployment elasticsearch-operator -o template --template={{ replica_status }} -n {{ ocp_project }}
  register: resource_status
  ignore_errors: true

- block:
    - name: "Install elasticsearch operator in {{ ocp_project }}"
      shell: |
        {{ openshift_cli }} create -n {{ ocp_project }} -f {{ elasticsearch_files_url }}/01-service-account.yaml
        {{ openshift_cli }} create -n {{ ocp_project }} -f {{ elasticsearch_files_url }}/02-role.yaml
        {{ openshift_cli }} create -n {{ ocp_project }} -f {{ elasticsearch_files_url }}/03-role-bindings.yaml
        {{ openshift_cli }} create -n {{ ocp_project }} -f {{ elasticsearch_files_url }}/04-crd.yaml
        {{ openshift_cli }} create -n {{ ocp_project }} -f {{ elasticsearch_files_url }}/05-deployment.yaml

    - name: "Wait until elasticsearch operator is active in {{ ocp_project }}"
      shell: "{{ openshift_cli }} get deployment elasticsearch-operator -o template --template={{ json_template }} -n {{ ocp_project }}"
      vars:
        json_template: '\{\{.status.readyReplicas\}\}'
      register: result
      until: result.stdout == "1"
      retries: 30
      delay: 10
      changed_when: false

  when: >
    resource_status.stdout is not defined or 
    resource_status.stdout is none or
    resource_status.stdout != "1"

