---

- shell: |
    {{ openshift_cli }} get deployment elasticsearch-operator -o template --template={{ replica_status }} -n {{ ocp_project }}
  register: resource_status
  ignore_errors: true

- block:

  - name: get default channel for elasticsearch operator
    shell: |-
      oc get packagemanifests {{ elasticsearch_operator_package_name }} -o jsonpath='{.status.defaultChannel}'
    register: es_defaultchannel

  - name: get currentCSV for default channel
    shell: |-
      oc get packagemanifests {{ elasticsearch_operator_package_name }} -o jsonpath='{.status.channels[?(@.name == "{{ es_defaultchannel.stdout }}")].currentCSV}'
    register: es_currentCSV
  
  - name: set ES startingCSV
    set_fact:
      elasticsearch_operator_startingcsv: "{{ es_currentCSV.stdout }}"

  - name: set ES operator channel
    set_fact:
      elasticsearch_operator_channel: "{{ es_defaultchannel.stdout }}"

  - name: "copy {{ resources_base_dir }}/elasticsearch/subscription.yml"
    template:
      src: "{{ resources_base_dir }}/elasticsearch/subscription.yml"
      dest: "{{ work_dir }}/elasticsearch-subscription.yml"

  - name: "Create operatorgroups in {{ ocp_project }}"
    k8s:
      state: present
      namespace: "{{ ocp_project }}"
      src: "{{ resources_base_dir }}/operatorgroup/operatorgroup.yml"

  - name: "Create elasticsearch subscription"
    k8s:
      state: present
      namespace: "{{ ocp_project }}"
      src: "{{ work_dir }}/elasticsearch-subscription.yml"

  - name: "Wait until elasticsearch operator is active"
    shell: "oc get deployment elasticsearch-operator -o template --template={{ json_template }} -n {{ ocp_project }}"
    vars:
      json_template: '\{\{.status.readyReplicas\}\}'
    register: result
    until: result.stdout == "1"
    retries: 30
    delay: 10
    changed_when: false

  when: >
    resource_status.stdout is not defined or 
    resource_status.stdout is none or
    resource_status.stdout != "1"


