---

- name: "copy and filter openshift resource resources/openshift/project.yml "
  template:
    src: "{{ resources_base_dir }}/openshift/project.yml"
    dest: "{{ work_dir }}/project.yml"

- name: create project {{ ocp_project }}
  k8s:
    state: present
    src: "{{ work_dir }}/project.yml"

- name: assign user {{ project_admin }} as project admin in {{ ocp_project }}
  shell:  "oc adm policy add-role-to-user admin {{ project_admin }} -n {{ ocp_project }}"
  when: >
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""
