apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
spec:
  channel: '{{ kiali_operator_channel }}'
  installPlanApproval: Automatic
  name: {{ kiali_operator_package_name }}
  source: {{ kiali_operator_catalog_source }}
  sourceNamespace: {{ kiali_operator_catalog_source_namespace }}
  startingCSV: {{ kiali_operator_startingcsv }}
