---

- shell: |
    {{ openshift_cli }} get deployment jaeger-operator -o template --template={{ replica_status }} -n {{ ocp_project }}
  register: resource_status
  ignore_errors: true

- block:
  - name: "copy {{ resources_base_dir }}/jaeger/subscription.yml"
    template:
      src: "{{ resources_base_dir }}/jaeger/subscription.yml"
      dest: "{{ work_dir }}/jaeger-subscription.yml"

  - name: "Create operatorgroups in {{ ocp_project }}"
    k8s:
      state: present
      namespace: "{{ ocp_project }}"
      src: "{{ resources_base_dir }}/operatorgroup/operatorgroup.yml"

  - name: "Create jaeger subscription"
    k8s:
      state: present
      namespace: "{{ ocp_project }}"
      src: "{{ work_dir }}/jaeger-subscription.yml"

  - name: "Wait until jaeger operator is active"
    shell: "oc get deployment jaeger-operator -o template --template={{ json_template }} -n {{ ocp_project }}"
    vars:
      json_template: '\{\{.status.readyReplicas\}\}'
    register: result
    until: result.stdout == "1"
    retries: 30
    delay: 10
    changed_when: false

  when: >
    resource_status.stdout is not defined or
    resource_status.stdout is none or
    resource_status.stdout != "1"
