apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
spec:
  channel: '{{ maistra_operator_channel }}'
  installPlanApproval: Automatic
  name: {{ maistra_operator_package_name }}
  source: {{ maistra_operator_catalog_source }}
  sourceNamespace: {{ maistra_operator_catalog_source_namespace }}
  startingCSV: {{ maistra_operator_startingcsv }}
