apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
spec:
  channel: '{{ jaeger_operator_channel }}'
  installPlanApproval: Automatic
  name: {{ jaeger_operator_package_name }}
  source: {{ jaeger_operator_catalog_source }}
  sourceNamespace: {{ jaeger_operator_catalog_source_namespace }}
  startingCSV: {{ jaeger_operator_startingcsv }}