apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: er-demo-user-and-admins-provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: erdemo-admins-secret
